### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Bazmundi** [pawamoy/archan#35]
What work is there to port this to windows?

**Comment by Pawamoy** [comment]
Did you try to use it / install it on Windows? How did it go? I do not have a Windows machine available right now so I can't try.

Or maybe you are just referring to the package classifiers?

**Comment by Bazmundi** [comment]
No. Installed on windows.  I got some errors come up when trying to run
things.  Uses linux idioms etc.

**Comment by Pawamoy** [comment]
Could you share these errors? I'm gonna spin up a VM later to see by myself.

**Comment by pawamoy** [comment]
Lack of info, closing.
